#! /bin/bash
#
# chkconfig: 2345 99 99
# description: Continues running Auto Cert Kit if an operation cause a reboot


log() {
# Log to syslog
logger -t "auto-cert-kit" $1
# Print to serial console
echo $1
}

start() {

ack_dir="/opt/xensource/packages/files/auto-cert-kit"

tests=$ack_dir/test_run.conf

while ! pidof /opt/xensource/bin/xapi >/dev/null
do
	log "Waiting for XAPI to startup..."
	sleep 1s
done
#sleep for a few seconds to make sure XAPI is fully up
sleep 10s 
if [ -e "$tests" ]
then
    log "Executing test_runner.py"
    python $ack_dir/test_runner.py -t $tests
else
    log "Nothing to do."
fi

}

stop() {
#Nothing, do nothing
log "Stopping"
}

restart() {
	 stop
	 start
}

case "$1" in
     start)
	start
	;;
     stop)
        stop
	;;
     restart)
        restart
	;;
     *)
        echo "Usage: $0 {start|stop|restart}"
esac

exit 0
